name: Build ClipForge APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Instalar sistema
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk autoconf libtool pkg-config libncurses5-dev libffi-dev libssl-dev cmake
      - name: Instalar Python
        run: pip3 install buildozer cython kivy==2.3.0 kivymd==1.2.0 pillow plyer
      - name: Compilar APK
        run: yes | buildozer android debug 2>&1
      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: ClipForge-APK
          path: bin/*.apk
